[package]
name = "wasm-pack"
description = "ðŸ“¦âœ¨ your favorite rust -> wasm workflow tool!"
version = "0.10.3"
authors = ["Ashley Williams <ashley666ashley@gmail.com>", "Jesper HÃ¥kansson <jesper@jesperh.se>"]
repository = "https://github.com/rustwasm/wasm-pack.git"
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
categories = ["wasm"]
documentation = "https://rustwasm.github.io/wasm-pack/"

[dependencies]
anyhow = "1.0.68"
atty = "0.2.14"
binary-install = "0.1.0"
cargo_metadata = "0.15.2"
chrono = "0.4.23"
console = "0.15.5"
curl = "0.4.44"
dialoguer = "0.10.3"
env_logger = { version = "0.10.0", default-features = false }
glob = "0.3.1"
human-panic = "1.0.3"
log = "0.4.17"
openssl = { version = '0.10.45', optional = true }
parking_lot = "0.12.1"
reqwest = { version = "0.11.14", features = ["blocking"] }
semver = "1.0.16"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_ignored = "0.1.7"
serde_json = "1.0.91"
siphasher = "0.3.10"
strsim = "0.10.0"
structopt = "0.3.26"
toml = "0.5.11"
walkdir = "2.3.2"
which = "4.4.0"

[dev-dependencies]
assert_cmd = "2.0.8"
lazy_static = "1.4.0"
predicates = "2.1.5"
serial_test = "1.0.0"
tempfile = "3.3.0"

[features]
# OpenSSL is vendored by default, can use system OpenSSL through feature flag.
default = ['openssl/vendored']

# Treat compiler warnings as a build error.
# This only runs in CI by default
strict = ['openssl/vendored']
sys-openssl = ['openssl']
# Keeping feature for users already using this feature flag
vendored-openssl = ['openssl/vendored']
