[package]
name = "wasm-pack"
description = "pack up the wasm and publish it to npm!"
version = "0.1.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/wasm-pack.git"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
failure = "0.1.1"
quicli = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
