[package]
name = "wasm-pack"
description = "pack up the wasm and publish it to npm!"
version = "0.2.0"
authors = ["Ashley Williams <ashley666ashley@gmail.com>"]
repository = "https://github.com/ashleygwilliams/wasm-pack.git"
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
console = "0.6.1"
failure = "0.1.1"
human-panic = "0.4.0"
indicatif = "0.9.0"
lazy_static = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
toml = "0.4"
